package io.vertx.nms.agent.database;

enum SqlQuery {

  // FACES
  CREATE_FACES_TABLE, ALL_FACES, GET_FACE, CREATE_FACE, SAVE_FACE, DELETE_FACE, DELETE_ALL_FACES, GET_FACE_BY_ID,

  // FIB
  CREATE_FIB_TABLE, ALL_FIB, GET_FIB_ENTRY, CREATE_FIB_ENTRY, SAVE_FIB_ENTRY, DELETE_FIB_ENTRY, GET_FIB_BY_PREFIX

}
